services:
  api:
    build: api
    # comment this out when not running docker rootless
    user: root
    volumes:
      - ./api/src:/app
      - ./api/gems:/gems
    ports:
      - "5000:5000"
    depends_on:
      - database